In [1]:
from skimage.io import imread, imshow
from skimage.transform import resize
from skimage.feature import hog
from skimage import exposure, color
import matplotlib.pyplot as plt
%matplotlib inline
import math
import numpy as np

In [68]:
def calculateIntersection(hI, hM):
    intersection = 0
    for i in range(len(hI)):
        intersection += (hI[i] - hM[i]) * (hI[i] - hM[i])
    return math.sqrt(intersection)

In [50]:
index = ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10']

In [101]:
fds = {}
fds['hoa dâm bụt'] = []
fds['hoa anh túc'] = []
fds['hoa anh thảo'] = []
fds['hoa bướm'] = []
fds['hoa hồng đá'] = []
fds['hoa dã quỳ'] = []
fds['hoa đồng tiền'] = []
fds['hoa hướng dương'] = []
fds['hoa cúc']= []

In [102]:
for i in fds.keys():
    name = i.split(' -')[0]
    for j in index:
        img = imread(f'Flower\{i}\{name}{j}.png')
        # fd, hog_image = hog(img, orientations=9, pixels_per_cell=(8, 8), cells_per_block=(2, 2), visualize=True, multichannel=True)
        # fds[f'{i}'].append(fd)
        
        
# fds

C:\Users\khanh\AppData\Local\Temp\ipykernel_19800\1989063327.py:5: FutureWarning: `multichannel` is a deprecated argument name for `hog`. It will be removed in version 1.0. Please use `channel_axis` instead.
  fd, hog_image = hog(img, orientations=9, pixels_per_cell=(8, 8), cells_per_block=(2, 2), visualize=True, multichannel=True)


{'hoa dâm bụt': [array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0.        , 0.        , 0.        , ..., 0.07689812, 0.07145216,
         0.13479787]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.])],
 'hoa anh túc': [array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.])],
 'hoa anh thảo': [array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  array([0., 0.

In [103]:
def kNearestNeighbor(trainSet, point, k):
    distances = []
    for i in trainSet.keys():
        for j in fds[i]:
            distance = calculateIntersection(j, fd)
            distances.append((distance, i))
    distances.sort()
    arr = [x[1] for x in distances]
    print(arr[:k])
    return arr[:k]

In [104]:
def findMostOccur(arr):
    labels = set(arr) # set label
    ans = ""
    maxOccur = 0
    for label in labels:
        num = arr.count(label)
        if num > maxOccur:
            maxOccur = num
            ans = label
    return ans

In [105]:
import os
true_predict = 0
false_predict = 0
for file in os.listdir("Flower/test"):
    filename = os.path.join("Flower/test", file)
    img_test = imread(filename)
    img_test = resize(img_test, (128,128))
    fd, hog_image_test = hog(img_test, orientations=9, pixels_per_cell=(8, 8), cells_per_block=(2, 2), visualize=True, multichannel=True)
    distances = kNearestNeighbor(fds, fd, 5)
    print(file)
    if findMostOccur(distances) == file[:-6]:
        true_predict += 1
    else:
        false_predict += 1
true_predict / (true_predict + false_predict)

C:\Users\khanh\AppData\Local\Temp\ipykernel_19800\3042728438.py:8: FutureWarning: `multichannel` is a deprecated argument name for `hog`. It will be removed in version 1.0. Please use `channel_axis` instead.
  fd, hog_image_test = hog(img_test, orientations=9, pixels_per_cell=(8, 8), cells_per_block=(2, 2), visualize=True, multichannel=True)


['hoa anh thảo', 'hoa dâm bụt', 'hoa anh túc', 'hoa dâm bụt', 'hoa dâm bụt']
hoa anh thảo01.png
['hoa anh túc', 'hoa hồng đá', 'hoa anh túc', 'hoa hồng đá', 'hoa anh túc']
hoa anh thảo02.png
['hoa anh túc', 'hoa anh thảo', 'hoa anh túc', 'hoa dâm bụt', 'hoa anh túc']
hoa anh túc01.png
['hoa anh túc', 'hoa anh túc', 'hoa hồng đá', 'hoa hồng đá', 'hoa anh thảo']
hoa anh túc02.png
['hoa đồng tiền', 'hoa cúc', 'hoa đồng tiền', 'hoa cúc', 'hoa đồng tiền']
hoa bướm01.png
['hoa bướm', 'hoa bướm', 'hoa đồng tiền', 'hoa đồng tiền', 'hoa anh thảo']
hoa bướm02.png
['hoa hướng dương', 'hoa hướng dương', 'hoa cúc', 'hoa đồng tiền', 'hoa đồng tiền']
hoa cúc01.png
['hoa cúc', 'hoa anh túc', 'hoa đồng tiền', 'hoa đồng tiền', 'hoa dã quỳ']
hoa cúc02.png
['hoa dâm bụt', 'hoa dâm bụt', 'hoa dâm bụt', 'hoa đồng tiền', 'hoa dâm bụt']
hoa dâm bụt01.png
['hoa dâm bụt', 'hoa đồng tiền', 'hoa dâm bụt', 'hoa đồng tiền', 'hoa hướng dương']
hoa dâm bụt02.png
['hoa cúc', 'hoa đồng tiền', 'hoa cúc', 'hoa cúc', 'hoa

0.2692307692307692